#!/usr/bin/env python3
"""One-off: add developer credit to report template footers."""
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OLD = "<footer>Generated by Req2Release</footer>"
NEW = "<footer>Generated by Req2Release Â· Developed by Mayur Gunjal</footer>"

for rel in (
    ".cursor/skills/coverage-validator/report-template.html",
    "pegasus-qa-agents-lab/.cursor/skills/coverage-validator/report-template.html",
):
    path = ROOT / rel
    if not path.exists():
        continue
    text = path.read_text(encoding="utf-8")
    if OLD in text:
        path.write_text(text.replace(OLD, NEW, 1), encoding="utf-8")
        print("ok", path)
    elif NEW in text:
        print("skip", path)
